apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "elasticsearch-operator.fullname" . }}
  labels:
    app: {{ template "elasticsearch-operator.name" . }}
    chart: {{ template "elasticsearch-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "elasticsearch-operator.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "elasticsearch-operator.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/sh"]
        args: ["-c", "/usr/local/bin/elasticsearch-operator -initDaemonsetNamespace $(NAMESPACE)"]
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
